config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  devise_for :users
  root 'notes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/note.rb
class Note < ApplicationRecord

    mount_uploader :image, ImageUploader
  def self.search(search)
      where("title ILIKE ? OR body ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @note = Note.new
    if params[:search]
      @notes = Note.search(params[:search]).order("created_at DESC")
    elsif params[:id]
      @note= Note.find(params[:id])
    else
      @note = Note.last
      @notes = Note.all.order("created_at DESC")
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @notes = Note.all

  end

  # GET /notes/new
  def new
    @notes = Note.all

    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
      @notes = Note.all
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navbar.html.erb
<%= nav_bar fixed: :top, brand: "Notebook", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%#= drop_down "Products" do %>
            <%#= menu_item "Things you can't afford", expensive_products_path %>
            <%# if current_user.lives_in_hackney? %>
            <%#= menu_item "Bikes", fixed_wheel_bikes_path %>
            <%# end %>
        <%# end %>
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
        <%#= render "layouts/navbar" %>
         <div class="col-md-1 sidebar ">
            <ul>



              <li><a href="#newnote" data-toggle="modal"><span class="glyphicon glyphicon-plus" aria-hidden= "true"></span></a></li>
              <li><a href="#search" data-toggle="modal"><span class="glyphicon glyphicon-search" aria-hidden= "true"></span></a></li>
              <li></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h3> Notes </h3>
            <div class="row">
                <div class="col-md-5"><%= @notes.count %></div>
                <div class="col-md-7">filter</div>
            </div>
        <hr>
          <div class="row ">
              <% @notes.each do |note| %>
                  <strong id="<%= note.id %>"><%= link_to note.title, edit_note_path(note) %></a></strong>
                  <br>
                  <%= note.created_at %>
                  <br>
                  <%= truncate(note.body, length: 100) %>
                  <hr>
              <% end %>
          </div>
        </div>
        <div class="col-md-8">
            <%= yield %>
        </div>
    </div>
    <!-- Modal start here -->
            <div class="modal fade modal-fullscreen" id="newnote" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

              <div class="modal-body">
                <%= render 'notes/form' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
        <!-- Modal search here -->
               <div class="modal fade modal-fullscreen" id="search" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
             <div class="modal-dialog" role="document">
               <div class="modal-content">
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                 <div class="modal-body">
                   <%= form_tag(notes_path, :method => "get", id: "search-form") do %>
                       <%= text_field_tag :search, params[:search], placeholder: "Search notes" %>
                       <%= submit_tag "Search", :name => nil %>
                    <% end %>
                 </div>
                 <div class="modal-footer">
                   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                   <button type="button" class="btn btn-primary">Save changes</button>
                 </div>
               </div>
             </div>
           </div>


  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, :html => { :class => "form-horizontal note" } do |f| %>

    <% if @note.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@note.errors.count, "error") %>
                    prohibited this note from being saved:</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <% @note.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <div class="form-group">
        <div class="col-lg-10">
            <%= f.text_field :title, :class => 'form-control' %>
        </div>
        <%=f.error_span(:title) %>
    </div>
    <div class="form-group">
        <div class="col-lg-10">
            <%= f.cktext_area :body, :class => 'form-control' %>
        </div>
        <%=f.error_span(:body) %>
    </div>

    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <%= f.submit nil,class: 'btn btn-primary' %>
            <%#= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    notes_path, :class => 'btn btn-default' %>
        </div>
    </div>

<% end %>

app/views/notes/edit.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/index.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

      <%= render 'form' %>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      note_path(@note), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_note_path(@note), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      note_path(@note),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_note_path,
            :class => 'btn btn-primary' %>


            <% if @notes.blank? %>
                <h4>There are no recipes containing the term <%= params[:search] %>.</h4>
            <% end %>

app/views/notes/new.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/show.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @note.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @note.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              notes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_note_path(@note), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              note_path(@note),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>